/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.gui;

/**
 *
 * @author krist
 */
public class Registration_gui extends javax.swing.JFrame {

    /**
     * Creates new form Registration
     * @return 
     */
    public void Registration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register_title = new javax.swing.JLabel();
        Firstname_input = new javax.swing.JTextField();
        firstname_label = new javax.swing.JLabel();
        surname_label = new javax.swing.JLabel();
        Firstname_input1 = new javax.swing.JTextField();
        gender_male_check = new javax.swing.JCheckBox();
        Gender_label = new javax.swing.JLabel();
        gender_female_check = new javax.swing.JCheckBox();
        gender_other_check = new javax.swing.JCheckBox();
        gender_pnts_check = new javax.swing.JCheckBox();
        DOB_picker = new com.toedter.calendar.JCalendar();
        DOB_label = new javax.swing.JLabel();
        Phone_label = new javax.swing.JLabel();
        Phone_input = new javax.swing.JTextField();
        Doctor_label = new javax.swing.JLabel();
        Doctor_list = new javax.swing.JComboBox<>();
        Details_Label = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        detail_input = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 800));
        setPreferredSize(new java.awt.Dimension(900, 800));
        setSize(new java.awt.Dimension(900, 800));

        Register_title.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        Register_title.setText("Register");
        Register_title.setToolTipText("");

        Firstname_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Firstname_inputActionPerformed(evt);
            }
        });

        firstname_label.setText("First Name");

        surname_label.setText("Surname");
        surname_label.setToolTipText("");

        Firstname_input1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Firstname_input1ActionPerformed(evt);
            }
        });

        gender_male_check.setText("Male");
        gender_male_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_male_checkActionPerformed(evt);
            }
        });

        Gender_label.setText("Gender");

        gender_female_check.setText("Female");
        gender_female_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_female_checkActionPerformed(evt);
            }
        });

        gender_other_check.setText("Other");
        gender_other_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_other_checkActionPerformed(evt);
            }
        });

        gender_pnts_check.setText("Prefer not to say");
        gender_pnts_check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender_pnts_checkActionPerformed(evt);
            }
        });

        DOB_picker.setDate(new java.util.Date(1678286232000L));

        DOB_label.setText("Date of Birth");

        Phone_label.setText("Phone Number");

        Phone_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Phone_inputActionPerformed(evt);
            }
        });

        Doctor_label.setText("Doctor Choosen");

        Doctor_list.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dr Smith", "Dr Jason", "Dr Andrew" }));
        Doctor_list.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Doctor_listActionPerformed(evt);
            }
        });

        Details_Label.setText("Details");

        detail_input.setColumns(1);
        detail_input.setLineWrap(true);
        detail_input.setRows(5);
        detail_input.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        detail_input.setDragEnabled(true);
        detail_input.setName(""); // NOI18N
        jScrollPane1.setViewportView(detail_input);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(347, 347, 347)
                .addComponent(Register_title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(369, 369, 369))
            .addGroup(layout.createSequentialGroup()
                .addGap(304, 304, 304)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Doctor_label)
                    .addComponent(Phone_label)
                    .addComponent(DOB_label)
                    .addComponent(DOB_picker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Gender_label)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(gender_male_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender_female_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender_other_check)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gender_pnts_check))
                    .addComponent(surname_label)
                    .addComponent(Firstname_input1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(firstname_label)
                    .addComponent(Firstname_input, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Details_Label)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Doctor_list, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Phone_input, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(Register_title)
                .addGap(18, 18, 18)
                .addComponent(firstname_label)
                .addGap(1, 1, 1)
                .addComponent(Firstname_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(surname_label)
                .addGap(1, 1, 1)
                .addComponent(Firstname_input1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(Gender_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(gender_male_check)
                    .addComponent(gender_female_check)
                    .addComponent(gender_other_check)
                    .addComponent(gender_pnts_check))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(DOB_picker, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Phone_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Phone_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Doctor_label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Doctor_list, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Details_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(128, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Firstname_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Firstname_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Firstname_inputActionPerformed

    private void Firstname_input1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Firstname_input1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Firstname_input1ActionPerformed

    private void gender_male_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_male_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_male_checkActionPerformed

    private void gender_female_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_female_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_female_checkActionPerformed

    private void gender_other_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_other_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_other_checkActionPerformed

    private void gender_pnts_checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender_pnts_checkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender_pnts_checkActionPerformed

    private void Phone_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Phone_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Phone_inputActionPerformed

    private void Doctor_listActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Doctor_listActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Doctor_listActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registration.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registration().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel DOB_label;
    private com.toedter.calendar.JCalendar DOB_picker;
    private javax.swing.JLabel Details_Label;
    private javax.swing.JLabel Doctor_label;
    private javax.swing.JComboBox<String> Doctor_list;
    private javax.swing.JTextField Firstname_input;
    private javax.swing.JTextField Firstname_input1;
    private javax.swing.JLabel Gender_label;
    private javax.swing.JTextField Phone_input;
    private javax.swing.JLabel Phone_label;
    private javax.swing.JLabel Register_title;
    public javax.swing.JTextArea detail_input;
    private javax.swing.JLabel firstname_label;
    private javax.swing.JCheckBox gender_female_check;
    private javax.swing.JCheckBox gender_male_check;
    private javax.swing.JCheckBox gender_other_check;
    private javax.swing.JCheckBox gender_pnts_check;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel surname_label;
    // End of variables declaration//GEN-END:variables
}
